kind: pipeline
name: test_1

steps:
- name: Install deps
  image: python:3
  commands:
  - pip3 install -r requirements.txt

- name: Run some stuff
  image: python:3
  commands:
  - uname -a
  - ls -la
  - sleep 1

- name: Deployment
  image: python:3
  commands:
  - python:3 -c "print('DEPLOYING!')"

